mode = 'Test'

[model]
model_type = 'GAT_LP'
node_dim = 1024
hidden_dim = 512
output_dim = 256

[optimizer]
learning_rate = 1e-3
weight_decay = 5e-5

[scheduler]
#step_size=40000
#gamma=0.5

[dataset]
train_dataset_dirpath = "/root/autodl-tmp/link_dataset/node/initial_nl1_el1/train"
valid_dataset_dirpath = "/root/autodl-tmp/link_dataset/node/initial_nl1_el1/valid"
test_dataset_dirpath =  "/root/autodl-tmp/link_dataset/node/initial_nl1_el1/test"
encode_type = 'node'
seed = 1234

worker_number = 32

[api]
meta_filepath = ""
onnx_model_dirpath = ""

[logging]
name = "GAT_LP_node"
mode = "both"
filepath = "./gat_lp_node.log"

