mode = 'Test'

[model]
model_type = 'GCN_LP'
node_dim = 1024
hidden_dim = 512
output_dim = 256

[optimizer]
learning_rate = 1e-4
weight_decay = 5e-5

[scheduler]
#step_size=40000
#gamma=0.5

[dataset]
train_dataset_dirpath = "/root/autodl-tmp/link_dataset/operator/initial_nl1_el1/train"
valid_dataset_dirpath = "/root/autodl-tmp/link_dataset/operator/initial_nl1_el1/valid"
test_dataset_dirpath =  "/root/autodl-tmp/link_dataset/operator/initial_nl1_el1/test"
encode_type = 'operator'
seed = 1234

worker_number = 32

[api]
meta_filepath = ""
onnx_model_dirpath = ""

[logging]
name = "GCN_LP_operator"
mode = "both"
filepath = "./gcn_lp_operator.log"

