mode = 'Train'

[model]
model_type = 'GAE_NP'
stage = 'encoder'
ae_type = 'GAE'
node_dim = 1024
hidden_dim = 512

[optimizer]
learning_rate = 1e-4
weight_decay = 5e-5

[scheduler]
# step_size=40000
# gamma=0.5

[dataset]
train_dataset_dirpath = "/root/autodl-tmp/np/operator/train"
valid_dataset_dirpath = "/root/autodl-tmp/np/operator/valid"
test_dataset_dirpath =  "/root/autodl-tmp/np/operator/test"
encode_type = 'operator'
block_get_type = 'greedy_modularity_communities'
seed = 1234

worker_number = 64

[api]
meta_filepath = ""
onnx_model_dirpath = ""

[logging]
name = "gae_np_encoder_operator"
mode = "both"
filepath = "./gae_np_encoder_operator.log"

