mode = 'Test'

[model]
model_type = 'GAE_NP'
stage = 'classification'
ae_type = 'GAE'
node_dim = 1024
hidden_dim = 512
emb_checkpoint_path = '/root/autodl-tmp/Experiments/Node_prediction/checkpoint-gae-np/gae_np_encoder_node/gae_np_encoder_node_Epoch_65_Step_4000.cp'

[optimizer]
learning_rate = 1e-3
weight_decay = 5e-4

[scheduler]
# step_size=40000
# gamma=0.5

[dataset]
train_dataset_dirpath = "/root/autodl-tmp/np/node/train"
valid_dataset_dirpath = "/root/autodl-tmp/np/node/valid"
test_dataset_dirpath =  "/root/autodl-tmp/np/node/test"
encode_type = 'node'
block_get_type = 'greedy_modularity_communities'
seed = 1234

worker_number = 32

[api]
meta_filepath = ""
onnx_model_dirpath = ""

[logging]
name = "gae_np_classification_node"
mode = "both"
filepath = "./gae_np_classification_node.log"

