mode = 'Test'

[model]
model_type = 'SAGE_NP'
node_dim = 1024
hidden_dim = 512


[optimizer]
learning_rate = 1e-3
weight_decay = 5e-5

[scheduler]
# step_size=40000
# gamma=0.5

[dataset]
train_dataset_dirpath = "/root/autodl-tmp/np/node/train"
valid_dataset_dirpath = "/root/autodl-tmp/np/node/valid"
test_dataset_dirpath =  "/root/autodl-tmp/np/node/test"
block_get_type = 'greedy_modularity_communities'
encode_type = 'node'
seed = 1234

worker_number = 32

[api]
meta_filepath = ""
onnx_model_dirpath = ""

[logging]
name = "SAGE_NP_node"
mode = "both"
filepath = "./sage_np_node.log"

