mode = 'Test'

[model]
model_type = 'VGAE_NP'
stage = 'classification'
ae_type = 'VGAE'
node_dim = 1024
hidden_dim = 512
emb_checkpoint_path = '/root/autodl-tmp/Experiments/Node_prediction/checkpoint-vgae-np/vgae_np_encoder_operator/vgae_np_encoder_operator_Epoch_86_Step_4000.cp'

[optimizer]
learning_rate = 1e-3
weight_decay = 5e-4

[scheduler]
# step_size=40000
# gamma=0.5

[dataset]
train_dataset_dirpath = "/root/autodl-tmp/np/operator/train"
valid_dataset_dirpath = "/root/autodl-tmp/np/operator/valid"
test_dataset_dirpath =  "/root/autodl-tmp/np/operator/test"
encode_type = 'operator'
block_get_type = 'greedy_modularity_communities'
seed = 1234

worker_number = 32

[api]
meta_filepath = ""
onnx_model_dirpath = ""

[logging]
name = "vgae_np_classification_operator"
mode = "both"
filepath = "./vgae_np_classification_operator.log"
