mode = 'Train'

[model]
model_type = 'VGAE_NP'
stage = 'encoder'
ae_type = 'VGAE'
node_dim = 1024
hidden_dim = 512

[optimizer]
learning_rate = 1e-4
weight_decay = 5e-5

[scheduler]
# step_size=40000
# gamma=0.5

[dataset]
train_dataset_dirpath = "/root/autodl-tmp/np/node/train"
valid_dataset_dirpath = "/root/autodl-tmp/np/node/valid"
test_dataset_dirpath =  "/root/autodl-tmp/np/node/test"
encode_type = 'node'
block_get_type = 'greedy_modularity_communities'
seed = 1234

worker_number = 64

[api]
meta_filepath = ""
onnx_model_dirpath = ""

[logging]
name = "vgae_np_encoder_node"
mode = "both"
filepath = "./vgae_np_encoder_node.log"

